doctrine:
    dbal:
        driver: 'pdo_mysql'
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        server_version: '8.0'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Products:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Products'
                prefix: 'Products\Entities'
                alias: Products
            Sales:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Sales'
                prefix: 'Sales\Entities'
                alias: Sales
            Stocks:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Stocks'
                prefix: 'Stocks\Entities'
                alias: Stocks
            Users:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Users'
                prefix: 'Users\Entities'
                alias: Users